site_name: Programação e Modelagem para Web
theme:
  name: material
  logo: 'images/typescript-logo.png'
  language: pt
  font:
    text: Roboto
    code: Roboto Mono
  palette: 
    - scheme: default
      media: "(prefers-color-scheme: dark)" # Config para que o default seja atribuido conforme o SO
      primary: '3776AB' # Azul para tema escuro
      accent: 'FFFFFF' # Branco como cor secundária
      toggle:
        icon: material/toggle-switch-off-outline
        name: Voltar a enxergar
    - scheme: slate 
      media: "(prefers-color-scheme: light)" # Config para que o default seja atribuido conforme o SO
      primary: 'FFFFFF' # Branco para tema claro
      accent: '3776AB' # Azul como cor secundária
      toggle:
        icon: material/toggle-switch
        name: Ficar cego  
  features: 
    - content.code.annotate
    - content.tabs.link
    - navigation.tabs        # TAB Superior
    - navigation.top         # Botão para voltar ao topo quando rolar para cima
    - search.highlight       # Faz um highlight no texto quando clicado após a pesquisa
    - search.share           # Coloca um botão para compartilhar a busca
    - navigation.indexes     # Permite a navegação para o index do menu
  not_found: index.md
